outscale/terraform-provider-outscale

- .github/workflows/generate_binaries_on_pr.yml
Generate and upload all artefacts.
Please Squash and merge.
> Github Action: Upload binaries on PR

- .github/workflows/acceptance_test.yml
- GNUmakefile
- on self-hosted runners
- pull_request_target to have access to secrets
> Github action: run acceptance test on PR

- .goreleaser.yml
- GNUmakefile
- outscale/config.go
- version/version.go
> Set Version in User-Agent

- outscale/resource_outscale_route_table_link.go
Signed-off-by: Thiery Ouattara <thiery.ouattara@outscale.com>
> TPD-2011: fix outscale_route_table_link import issue

- outscale/oapi_tags.go
Fixes #68
Signed-off-by: Thiery Ouattara <thiery.ouattara@outscale.
> Fix tags on outscale_resources

- outscale/data_source_outscale_public_ip.go
Fixes #65
Signed-off-by: Thiery Ouattara <thiery.ouattara@outscale.com>
> fix public_ip datasource filters

- outscale/data_source_outscale_image_export_task_test.go
- outscale/data_source_outscale_image_export_tasks_test.go
- outscale/data_source_outscale_public_ips_test.go
- outscale/data_source_outscale_server_certificate_test.go
- outscale/data_source_outscale_vm_state_test.go
- outscale/resource_outscale_access_key_test.go
- outscale/resource_outscale_image_export_task_test.go
- outscale/resource_outscale_internet_service_link_test.go
- outscale/resource_outscale_route_table_test.go
- outscale/resource_outscale_route_test.go
- outscale/resource_outscale_security_group_rule_test.go
- outscale/resource_outscale_tags_test.go
- outscale/resource_outscale_vm_test.go
Signed-off-by: Thiery Ouattara <thiery.ouattara@outscale.com>
> Fix acceptance tests

- outscale/data_source_outscale_volume.go
- outscale/data_source_outscale_volumes.go
- outscale/resource_outscale_volume.go
Signed-off-by: Thiery Ouattara <thiery.ouattara@outscale.com>
> set standard volume default iops

- CHANGELOG.md
- README.md
Signed-off-by: Thiery Ouattara <opensource@outscale.com>
> update README and CHANGELOG

- .github/workflows/acceptance_test.yml
- .github/workflows/integration_tests.yml
Signed-off-by: Thiery Ouattara <opensource@outscale.com>
> add frieza-clean to clean account after running tests

- outscale/resource_outscale_vm.go
fix #86
Signed-off-by: Matthias Gatto <matthias.gatto@outscale.com>
> vms: update only tags when posible

- scripts/docs/generate_doc_terraform.py
- scripts/docs/requirements.txt
Replace all CamelCase parameters to snake_case format in the decription of the documentation
> Change the description when parameters are quoted

- .github/scripts/doc-build.sh
Doc submodule as been moved to scripts/docs
> Fix doc generation

- scripts/docs/generate_doc_terraform.py
- Copy the index
- Update templates and resources path
> Update the path for the doc-templates

- outscale/data_source_outscale_net_access_points.go
> fix net_access_points datasource

- outscale/resource_outscale_security_group.go
Signed-off-by: Matthias Gatto <matthias.gatto@outscale.com>
> security-grouyp: add empty argument

- .github/workflows/examples-test.yml
- GNUmakefile
- scripts/test-examples.sh
> Example workflow

- scripts/test-examples.sh
Fix the examples workflow problem about versioning
> fix examples versioning

- outscale/data_source_outscale_image.go
- outscale/data_source_outscale_images.go
- outscale/resource_outscale_image.go
- outscale/resource_outscale_image_test.go
> Fix bsu on outscale_image block device mappings

- outscale/data_source_outscale_subregions.go
> Add locationcode in subregion

- outscale/data_source_outscale_vm.go
- outscale/resource_outscale_vm.go
- outscale/resource_outscale_vm_test.go
> Add CreationDate in VM

- outscale/data_source_outscale_snapshot.go
- outscale/data_source_outscale_snapshots.go
- outscale/resource_outscale_snapshot.go
> Add CreationDate in Snapshots

- outscale/data_source_outscale_vpn_connection.go
- outscale/data_source_outscale_vpn_connections.go
- outscale/resource_outscale_vpn_connection.go
- outscale/resource_outscale_vpn_connection_test.go
> Vgw telemetries vpnconnection

- outscale/data_source_outscale_public_catalog.go
- outscale/data_source_outscale_public_catalog_test.go
- outscale/provider.go
> Add Public catalog

- go.mod
- go.sum
- outscale/data_source_outscale_dhcp_option.go
- outscale/data_source_outscale_dhcp_option_test.go
- outscale/data_source_outscale_dhcp_options.go
- outscale/data_source_outscale_dhcp_options_test.go
- outscale/resource_outscale_dhcp_option.go
- outscale/resource_outscale_dhcp_option_test.go
> Logservers dhcpoptions

- outscale/resource_outscale_load_balancer_policy.go
- outscale/resource_outscale_load_balancer_policy_test.go
> Cookie expiration period in load balancer policy

- outscale/data_source_outscale_account.go
- outscale/data_source_outscale_account_test.go
- outscale/data_source_outscale_accounts.go
- outscale/data_source_outscale_accounts_test.go
- outscale/provider.go
> Account datasource

- outscale/data_source_outscale_load_balancer.go
- outscale/data_source_outscale_load_balancers.go
- outscale/resource_outscale_load_balancer.go
- outscale/resource_outscale_load_balancer_test.go
> SecuredCookie  and PublicIp in LoadBalancer

- outscale/data_source_outscale_vm.go
- outscale/resource_outscale_vm.go
- outscale/resource_outscale_vm_test.go
closes #155 
closes #141 
closes #144
> Add NestedVirtualization  in VM

- outscale/resource_outscale_vm.go
- outscale/resource_outscale_volume.go
- utils/utils.go
> allow setting iops on the right volume types

- outscale/resource_outscale_vm.go
> Fix user_data in vm

- outscale/resource_outscale_vm.go
> Remove iops parameter in block device mapping when it's in gp2

- outscale/resource_outscale_subnet.go
- outscale/resource_outscale_subnet_test.go
> Add update subnet

- outscale/resource_outscale_load_balancer_test.go
- outscale/resource_outscale_vm_test.go
Just fix the last fail in acceptance test.
> Fix test acc vm

- outscale/resource_outscale_volume.go
> Fix volume update error

- outscale/resource_outscale_vm.go
> Fix is_source_dest_checked on create VM

- examples/net_vm/vm.tf
- examples/public_load_balancer/vm.tf
- examples/public_vm/vm.tf
- examples/yunohost/vm.tf
> Fix authentification failures in exemples

- outscale/resource_outscale_image_export_task.go
- outscale/resource_outscale_snapshot_export_task.go
> Use terraform timeout for export task

- docs/index.md
Following the [Yaml Frontmatter](https://developer.hashicorp.com/terraform/registry/providers/docs#yaml-frontmatter) recommendations: update of the index.md file.
> DOC-3841: modified YAML Frontmatter

- .github/workflows/examples-test.yml
> Force examples workflow on eu-west-2

- outscale/data_source_outscale_vm_state.go
- outscale/data_source_outscale_vm_state_test.go
- outscale/data_source_outscale_vm_states.go
> Add all_vms in vm_state datasource(s)

- outscale/resource_outscale_access_key.go
> Fix access_key creation bug

- outscale/resource_outscale_client_gateway.go
- outscale/resource_outscale_image.go
- outscale/resource_outscale_internet_service.go
- outscale/resource_outscale_internet_service_link.go
- outscale/resource_outscale_load_balancer.go
- outscale/resource_outscale_load_balancer_listener_rule.go
- outscale/resource_outscale_nat_service.go
- outscale/resource_outscale_net.go
- outscale/resource_outscale_nic_link.go
- outscale/resource_outscale_subnet.go
- outscale/resource_outscale_virtual_gateway.go
- outscale/resource_outscale_virtual_gateway_link.go
- outscale/resource_outscale_vm.go
- outscale/resource_outscale_volume.go
- outscale/resource_outscale_volumes_link.go
- outscale/resource_outscale_vpn_connection.go
- outscale/resource_outscale_vpn_connection_route.go
- tests/qa_provider_oapi/data/flexible_gpu_catalog/TF-176_flexible_gpu_catalog_datasource_attributes_ok/step1.flexible_gpu_catalog_datasource_attributes_ok.ref
> Refactoring and update Delay in refresh functions

- .gitignore
- outscale/resource_outscale_security_group_rule.go
- tests/qa_provider_oapi/data/load_balancer_vm_health/TF-92_load_balancer_vm_health_datasource_attributes_ok/step1.load_balancer_vm_health_datasource_attributes_ok.ref
- tests/qa_provider_oapi/data/nets/TF-125_security_group_datasource_attributes_ok/step1.security_group_datasource_std_ok.ref
- tests/qa_provider_oapi/data/nets/TF-125_security_group_datasource_attributes_ok/step2.security_group_datasource_ok.ref
- tests/qa_provider_oapi/data/nets/TF-125_security_group_datasource_attributes_ok/step3.security_group_datasource_ok.ref
- tests/qa_provider_oapi/data/nets/TF-125_security_group_datasource_attributes_ok/step4.security_group_datasource_ok.ref
- tests/qa_provider_oapi/data/nets/TF-128_security_group_rule_resource_attributes_2_ok/step1.security_group_rule_resource_2_ok.ref
- tests/qa_provider_oapi/data/nets/TF-128_security_group_rule_resource_attributes_2_ok/step2.security_group_rule_resource_2_ok.ref
- tests/qa_provider_oapi/data/nets/TF-129_security_groups_datasource_attributes_ok/step1.security_groups_datasource_std_ok.ref
- tests/qa_provider_oapi/data/nets/TF-129_security_groups_datasource_attributes_ok/step2.security_groups_datasource_ok.ref
- tests/qa_provider_oapi/data/nets/TF-129_security_groups_datasource_attributes_ok/step3.security_groups_datasource_ok.ref
- tests/qa_provider_oapi/data/nets/TF-129_security_groups_datasource_attributes_ok/step4.security_groups_datasource_ok.ref
- tests/qa_provider_oapi/data/nets/TF-65_Check_IGW_Destroy/step1.test_destroy_igw.ref
- tests/qa_provider_oapi/data/security_group_rule/TF-127_security_group_rule_resource_attributes_ok/step1.security_group_rule_resource_ok.ref
- tests/qa_provider_oapi/data/security_group_rule/TF-127_security_group_rule_resource_attributes_ok/step3.security_group_rule_resource_ok.ref
closes https://github.com/outscale/terraform-provider-outscale/issues/286
> Remove other rules from security group rules

- outscale/provider.go
- outscale/resource_outscale_load_balancer_vms.go
- outscale/resource_outscale_load_balancer_vms_test.go
> Updates for outscale_load_balancer_vms

- outscale/resource_outscale_nat_service.go
> Fix crashed when NAT not found

- outscale/provider.go
- outscale/resource_outscale_main_route_table_link.go
- outscale/resource_outscale_main_route_table_link_test.go
- outscale/resource_outscale_route_table_link.go
- outscale/resource_outscale_route_table_link_test.go
- tests/qa_provider_oapi/data/flexible_gpu_catalog/TF-176_flexible_gpu_catalog_datasource_attributes_ok/step1.flexible_gpu_catalog_datasource_attributes_ok.ref
> Enable setting main route table

- examples/public_vm/outscale.tf
- examples/public_vm/volume.tf
- Fix the resource name in the example.
- Update version in example.
> volume_link for volumes_link

- README.md
> adding sed for net_peering

- .github/workflows/integration_tests.yml
- .github/workflows/nets_integ_tests.yml
- outscale/data_source_outscale_net_peering_test.go
- outscale/data_source_outscale_net_peerings_test.go
- outscale/resource_outscale_net_peering.go
- outscale/resource_outscale_net_peering_acceptation.go
- outscale/resource_outscale_net_peering_acceptation_test.go
- outscale/resource_outscale_net_peering_test.go
- tests/qa_provider_oapi/data/nets/TF-104_net_peering_datasource_attributes_ok/step1.net_peering_datasource_attributes_ok.ref
- tests/qa_provider_oapi/data/nets/TF-104_net_peering_datasource_attributes_ok/step1.net_peering_datasource_attributes_ok.tf
- tests/qa_provider_oapi/data/nets/TF-105_net_peering_resource_attributes_ok/step1.net_peering_resource_attributes_ok.ref
- tests/qa_provider_oapi/data/nets/TF-105_net_peering_resource_attributes_ok/step1.net_peering_resource_attributes_ok.tf
- tests/qa_provider_oapi/data/nets/TF-106_net_peering_acceptation_resource_attributes_ok/step1.net_peering_acceptation_resource_attributes_ok.ref
- tests/qa_provider_oapi/data/nets/TF-106_net_peering_acceptation_resource_attributes_ok/step1.net_peering_acceptation_resource_attributes_ok.tf
- tests/qa_provider_oapi/data/nets/TF-107_net_peerings_datasource_attributes_ok/step1.net_peerings_datasource_attributes_ok.ref
- tests/qa_provider_oapi/data/nets/TF-107_net_peerings_datasource_attributes_ok/step1.net_peerings_datasource_attributes_ok.tf
- tests/qa_provider_oapi/resources.auto.tfvars
- tests/qa_provider_oapi/variables.tf
- utils/utils.go
> Fix net_peering mandatory "accepter_owner_id" parameter.

- CHANGELOG.md
gitmoji for easy identification of changes / organizes information in a reader-friendly way
> :memo: docs: updated changelog

- outscale/resource_outscale_security_group_rule.go
- tests/qa_provider_oapi/data/subregions/TF-169_outscale_subregions_attributes_ok_no_filter/step1.outscale_subregions_attributes_ok_no_filter.ref
- tests/qa_provider_oapi/data/tests_iam_resources/TF011_policies_datasource_attributes_ok/step1.policies_datasource_attributes_ok.ref
> Fix ip_range validation for sg_rules

- outscale/oapi_tags.go
- outscale/resource_outscale_load_balancer.go
- tests/qa_provider_oapi/data/load_balancer/TF-79_public_load_balancer_resource_attributes_ok/step4.public_load_balancer_resource_update_listener_ok.ref
> :bug: Fix no error when adding certificateid to HTTP listener

- outscale/resource_outscale_nic.go
- outscale/resource_outscale_nic_test.go
- outscale/resource_outscale_vm_test.go
- tests/qa_provider_oapi/data/load_balancer_vm_health/TF-92_load_balancer_vm_health_datasource_attributes_ok/step1.load_balancer_vm_health_datasource_attributes_ok.ref
- tests/qa_provider_oapi/data/nets/TF-109_nic_datasource_attributes_ok/step1.nic_datasource_attributes_ok.ref
- tests/qa_provider_oapi/data/nets/TF-110_nic_resource_attributes_ok/step1.nic_resource_attributes_ok.ref
- tests/qa_provider_oapi/data/nets/TF-110_nic_resource_attributes_ok/step2.nic_resource_attributes_update.ref
- tests/qa_provider_oapi/data/nets/TF-111_nic_link_resource_attributes_ok/step1.nic_link_resource_attributes_ok.ref
- tests/qa_provider_oapi/data/nets/TF-112_nic_private_ip_resource_attributes_ok/step1.nic_private_ip_resource_attributes_ok.ref
- tests/qa_provider_oapi/data/nets/TF-113_nics_datasource_attributes_ok/step1.nics_datasource_attributes_ok.ref
- tests/qa_provider_oapi/data/nets/TF-145_vm_resource_private_with_multiple_NICs_attributes_ok/step1.vm_resource_private_with_multiple_NICs_ok.ref
- utils/utils.go
> :bug: Fix crash on nic configuration change

- outscale/resource_outscale_image.go
- outscale/resource_outscale_image_launch_permission_test.go
- outscale/resource_outscale_snapshot.go
- tests/qa_provider_oapi/data/load_balancer_vm_health/TF-92_load_balancer_vm_health_datasource_attributes_ok/step1.load_balancer_vm_health_datasource_attributes_ok.ref
- tests/qa_provider_oapi/data/snapshot/TF-130_snapshot_datasource_attributes_ok/step1.snapshot_datasource_attributes_ok.ref
- tests/qa_provider_oapi/data/snapshot/TF-131_snapshot_resource_attributes_ok/step1.snapshot_resource_attributes_ok.ref
- tests/qa_provider_oapi/data/snapshot_attributes/TF-132_snapshot_attributes_resource_attributes_ok/step1.snapshot_attributes_resource_attributes_ok.ref
- tests/qa_provider_oapi/data/snapshot_copy/TF-133_snapashot_c_resource_attributes_ok/step1.snapshot_copy_resource_attributes_ok.ref
- tests/qa_provider_oapi/data/snapshots/TF-134_snapshots_datasource_attributes_ok/step1.snapshots_datasource_attributes_ok.ref
- tests/qa_provider_oapi/data/vm/TF-146_vm_resource_public_with_BDM_attributes_ok/step1.vm_resource_public_with_multiple_BDM_ok.ref
- tests/qa_provider_oapi/data/vm/TF-146_vm_resource_public_with_BDM_attributes_ok/step2.vm_resource_public_with_multiple_BDM_ok.ref
- tests/qa_provider_oapi/data/volume/TF-155_volume_resource_attributes_ok3/step1.volume_resource_attributes_ok3.ref
> :recycle: Unable users to set snapshot timeout

- outscale/resource_keypair.go
> :bug: fix keypair resource when migration to terrafrom Framework

- outscale/provider.go
- outscale/resource_outscale_load_balancer_test.go
- tests/qa_provider_oapi/data/flexible_gpu_catalog/TF-176_flexible_gpu_catalog_datasource_attributes_ok/step1.flexible_gpu_catalog_datasource_attributes_ok.ref
> :bug: fix: panic with aliases of endpoints in providers

- outscale/data_source_outscale_net_peering.go
- tests/qa_provider_oapi/data/flexible_gpu_catalog/TF-176_flexible_gpu_catalog_datasource_attributes_ok/step1.flexible_gpu_catalog_datasource_attributes_ok.ref
> :bug: fix: catch empty datasource net_peering filter

- .github/workflows/cred-scan.yml
Please include a summary of the changes and the related context. If this is a feature, explain the motivation. If it's a bug fix, describe what was broken.
Fixes: #<issue-number> _(if applicable)_
Please check the relevant option(s):
Please describe the test strategy:
> 👷 ci: Update cred-scan workflow

- .goreleaser.yml
- Use github changelog for goreleaser
Please check the relevant option(s):
Please describe the test strategy:
Add any additional context or screenshots if necessary.
> :construction_worker: ci: use github changelog for goreleaser

- docs/resources/oks_cluster.md
To document:
outscale_oks_cluster resource
Corresponding OKS object: 
Resource: https://docs.outscale.com/oks.html#createcluster
I attached a generated markdown file with arguments and attributes, generated from the terraform code. In the file, `Read-Only` are the exported arguments, `Required` and `Optional` are the resource arguments.
Example:
```
Create a Cluster
resource "outscale_oks_project" "project01" {
name                    = "project01"
cidr                    = "10.50.0.0/18"
region                  = "eu-west-2"
} 
resource "outscale_oks_cluster" "cluster01" {
project_id              = outscale_oks_project.project01.id
admin_whitelist         = ["0.0.0.0/0"]
cidr_pods               = "10.91.0.0/16"
cidr_service            = "10.92.0.0/16"
version                 = "1.32" …
```
> 📝 docs: Adding OKS cluster resource
